name: cabyvocab
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cabyvocab_api
    ports:
      - '8081:8081'
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
